name: autotap_ai
description: AutoTap AI V3 (Macrorify-like) - Android 10+ - No autostart
publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
